name: Economy
main: com.minecraft.economy.economyMain.Economy
version: 1.6.1
commands:
  money:
    description: 金币余额
    usage: /money
  pay:
    description: 给其他玩家转账
    usage: /pay [玩家] [数字]
    permissions:
      pay.use:
        defailt: [false]
  givemoney:
    description: 给玩家钱
    usage: /givemoney [玩家] [数字]
    permissions:
      givemoney.use:
        defailt: [true]
  bank:
    description: 显示银行存款
    usage: /bank
  qk:
    description: 取款
    usage: /qk [金额]
  ck:
    description: 存款
    usage: /ck [金额]