#设置true为使用mysql数据库，设置false为使用yml储存数据
enableDataBase: false

'注释1请勿修改': '填写你的Host, 默认为Localhost'
host: localhost
'注释2请勿修改': '填写你的Mysql端口, 默认为3306'
port: 3306
'注释3请勿修改': '填写你的用户名，默认为root'
username: root
'注释4请勿修改': '填写你的密码'
password: root
'注释5请勿修改': '填写你需要连接的数据库'
database: minecraft

'注释8请勿修改': '是否开启银行利息'
enableInterest: true
'注释6请勿修改': '利率单位为万分之，只可以是整数！'
interestRate: 3
'注释7请勿修改': '每隔多长时间发一次利息 单位（秒）'
interestTime: 1800

'注释9请勿修改': '是否开启自动版本检查'
enable_version_check: true

'注释10请勿修改': '是否开启自动版本升级(必须同时开启自动版本检查)'
enable_auto_update: false

'注释11请勿修改': '初始金币数量'
initial_money: 1000