name: UltiEconomy
main: com.minecraft.economy.economyMain.UltiEconomyMain
version: ${project.version}
api-version: 1.13
loadbefore: [level, Ultimenu, UltiTools]
softdepend: [Vault, PlaceholderAPI]
load: STARTUP

commands:
  money:
    description: 货币余额
    usage: /money
  checkmoney:
    description: 检查玩家货币余额
    usage: /checkmoney
  checkbank:
    description: 检查玩家存款余额
    usage: /checkbank
  givemoney:
    description: 给玩家钱
    usage: /givemoney [玩家] [数字]
    permissions:
      givemoney.use:
        defailt: [true]
  takemoney:
    description: 拿走玩家的钱
    usage: /takemoney [玩家] [数字]
  setmoney:
    description: 设置玩家的钱
    usage: /setmoney [玩家] [数字]
  bank:
    description: 显示银行存款
    usage: /bank
  qk:
    description: 取款
    usage: /qk [金额]
  ck:
    description: 存款
    usage: /ck [金额]
  mvdb:
    description: 数据储存方法转换
    usage: /mvdb toLocal 启用存到本地 /mvdb toDataBase 启用存到数据库
